# Site
name: 'Artifact.se'
description: 'Artifact is a personal blog about my random projects in tech, knifemaking, art, and spirituality.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: 'admin@artifact.se'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    admin:
      name:           Admin
      #      site:           https://www.artifact.se
      avatar:         assets/images/avatar1.jpg
      bio:            "Cybersecurity student with a deep interest in tech, nature, cooking, art, and spirituality."
      email:          admin@artifact.se
      twitter:        https://x.com/artifact_se
    chatgpt:
      name:           ChatGpt
      #      site:           https://www.artifact.se
      avatar:         assets/images/avatar2.jpg
      bio:            "Content produced with the use of ChatGPT"
      email:          admin@artifact.se
      twitter:        https://x.com/artifact_se

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: admin
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
