# Site
name: 'Artifact.se'
description: 'Artifact is a personal blog about my random projects in tech, knifemaking, and art.'
motivational: 'The blacksmiths home only has wooden spoons.'
logo: 'assets/images/logo.png'
baseurl: ''
disqus: ''
email: 'admin@artifact.se'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    admin:
      name:           Admin
      avatar:         assets/images/profile_pic.jpg
      bio:            "Since high school, I've been fascinated by technology and computers. Over the years, I've delved into various areas such as programming, networking, and cybersecurity. My passion for learning has driven me to explore new technologies and stay updated with the latest trends in the tech world. In addition I have several hobbies including knifemaking, woodworking, and art."
      email:          mailto:fandersson50@gmail.com
      email-alt:      mailto:filip@artifact.se
      linkedin:       https://www.linkedin.com/in/foandersson
      github:         https://www.github.com/North14
      orcid:          https://orcid.org/0009-0001-2024-282X
    chatgpt:
      name:           ChatGpt
      site:           https://www.artifact.se
      avatar:         assets/images/avatar2.jpg
      bio:            "Content produced with the use of ChatGPT"

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: admin
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Collections
collections:
  knives:
    output: true
    permalink: /knives/:title/

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
